remote_theme : pages-themes/cayman

title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
url : "https://skypotato.github.io"
baseurl : ""