# Setup
title:        Skypotato's Blog
tagline:      Skypotato's Blog TEST
baseurl:      ""
paginate:     1
locale:       "ko"
# About/contact
author:
  name:       Skypotato
  url:        https://skypotato.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
